package cxfClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-12-13T23:29:15.656+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "autoName_service", 
                  wsdlLocation = "http://vs125.hand-china.com/trainitf/wsdl/modules/cux/PROYA/PUR_RFX/eitf_pur_rfx_export_to_erp_server.svc",
                  targetNamespace = "http://www.aurora-framework.org/schema") 
public class AutoNameService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.aurora-framework.org/schema", "autoName_service");
    public final static QName AutoNamePort = new QName("http://www.aurora-framework.org/schema", "autoName_port");
    static {
        URL url = null;
        try {
            url = new URL("http://vs125.hand-china.com/trainitf/wsdl/modules/cux/PROYA/PUR_RFX/eitf_pur_rfx_export_to_erp_server.svc");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AutoNameService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://vs125.hand-china.com/trainitf/wsdl/modules/cux/PROYA/PUR_RFX/eitf_pur_rfx_export_to_erp_server.svc");
        }
        WSDL_LOCATION = url;
    }

    public AutoNameService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AutoNameService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutoNameService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AutoNameService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AutoNameService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AutoNameService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns AutoNamePortType
     */
    @WebEndpoint(name = "autoName_port")
    public AutoNamePortType getAutoNamePort() {
        return super.getPort(AutoNamePort, AutoNamePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutoNamePortType
     */
    @WebEndpoint(name = "autoName_port")
    public AutoNamePortType getAutoNamePort(WebServiceFeature... features) {
        return super.getPort(AutoNamePort, AutoNamePortType.class, features);
    }

}
