
package xunjia;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "autoName_service", targetNamespace = "http://www.aurora-framework.org/schema", wsdlLocation = "http://vs125.hand-china.com/trainitf/wsdl/modules/ws_eitf/PUR_RFX/eitf_pur_rfx_export_to_erp_server.svc")
public class AutoNameService
    extends Service
{

    private final static URL AUTONAMESERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTONAMESERVICE_EXCEPTION;
    private final static QName AUTONAMESERVICE_QNAME = new QName("http://www.aurora-framework.org/schema", "autoName_service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://vs125.hand-china.com/trainitf/wsdl/modules/ws_eitf/PUR_RFX/eitf_pur_rfx_export_to_erp_server.svc");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTONAMESERVICE_WSDL_LOCATION = url;
        AUTONAMESERVICE_EXCEPTION = e;
    }

    public AutoNameService() {
        super(__getWsdlLocation(), AUTONAMESERVICE_QNAME);
    }

    public AutoNameService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTONAMESERVICE_QNAME, features);
    }

    public AutoNameService(URL wsdlLocation) {
        super(wsdlLocation, AUTONAMESERVICE_QNAME);
    }

    public AutoNameService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTONAMESERVICE_QNAME, features);
    }

    public AutoNameService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutoNameService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AutoNamePortType
     */
    @WebEndpoint(name = "autoName_port")
    public AutoNamePortType getAutoNamePort() {
        return super.getPort(new QName("http://www.aurora-framework.org/schema", "autoName_port"), AutoNamePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutoNamePortType
     */
    @WebEndpoint(name = "autoName_port")
    public AutoNamePortType getAutoNamePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.aurora-framework.org/schema", "autoName_port"), AutoNamePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTONAMESERVICE_EXCEPTION!= null) {
            throw AUTONAMESERVICE_EXCEPTION;
        }
        return AUTONAMESERVICE_WSDL_LOCATION;
    }

}
